### ISSUE TITLE
Is it possible to run PYNQ on z7045?

### ISSUE THREAD

**Issue by sadicLiu** [Xilinx/PYNQ#1070]
Hi, 
I found the support list of Development  Boards [here](http://www.pynq.io/board.html), and z7045 is not included, is it possible to run PYNQ on z7045?

**Comment by giunatale** [comment]
Hi @sadicLiu, as a reminder, we ask users to carefully read the issue template when creating a new issue. We request users to use the issue tracker only to report bugs and issues in the code. For all other questions, we have a dedicated forum: https://discuss.pynq.io/

Anyway, to reply to your question, the boards listed on the page you linked are the ones officially supported by PYNQ. There's a number of community projects for unofficial ports in the community section of our forum [here](https://discuss.pynq.io/t/3rd-party-images-for-zynq-boards/431), and documentation on how to port PYNQ onto a new board [here](https://gist.github.com/PeterOgden/9a5054a06408d2bd711d6de563281930) and in our official documentation [here](https://pynq.readthedocs.io/en/v2.5.1/pynq_sd_card.html#retargeting-to-a-different-board). 

I will close this issue due to our internal policies. If you have more questions, please open a thread on our forum. Thanks for your collaboration!
