### ISSUE TITLE
make boot_files BOARDS=ZCU102

### ISSUE THREAD

**Issue by EwardJohn** [Xilinx/PYNQ#1074]
* PYNQ version (e.g. v2.5):
* Board name (e.g. ZYNQ_Ultrascales+ zynq zcu102):
* Pull request type (bug fix / new feature):
* Pull request number:
* Description:
I use the code v2.5 to build images for ZCU102 with ZCU104 files,but when i do the "make boot_files BOARDS=ZCU102"  to obtain boot files it needs,a problem occurs.The problem is :    (I use the vivado 2019.1 version and petalinux 2019.1 version.)
![makeerro](https://user-images.githubusercontent.com/63114159/87660440-a32c5b80-c791-11ea-973d-daf168ab9b62.jpg)

So how do i solve the problem? Thanks

**Comment by giunatale** [comment]
Hi @EwardJohn, this is highly unlikely a bug, bur rather a misconfiguration on your end. I need to ask you to post this question on our support forum https://discuss.pynq.io, and upload the modified files from the ZCU104 board that you are using alongside a clear explanation of your issue.
We use the issue tracker here to report bugs that need acting on the code base. For anything else, we rely on the forum. I will close this issue for now.
If what has happened turns out to be an actual bug, you are more than welcome to open an issue here, detailing the bug encountered and filling the issue template properly.

Thanks for your collaboration.
