### ISSUE TITLE
i use browser to log in the board , but the password is invaild , it's not 'xilinx' ?

### ISSUE THREAD

**Issue by superFJH** [Xilinx/PYNQ#463]

**Comment by cathalmccabe** [comment]
Which browser are you using? Can you try using Chrome?

**Comment by superFJH** [comment]
chrome ,and used on Linux , but when i try to use pynq on win10 ,it worked .....

**Comment by superFJH** [comment]
oh , it can work on chrome , thanks. but why it can't be used on firefox ?

**Comment by PeterOgden** [comment]
The is a problem with Firefox when the date on the board is more than 30 days in the past. We set the date on the image when we upload it but unless the board has a way through DHCP or NTP  to update the time it will drift. If you update the time on the board using `sudo date -s "YYYY/MM/DD hh:mm:ss"` this will allow you to use Firefox. There's more details on the problem here https://groups.google.com/forum/#!msg/pynq_project/l3bKT9VSAmc/-CruhNIOAQAJ;context-place=forum/pynq_project.
